# -*- coding: utf-8 -*-
"""Netflix-Data-Analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15uEI0HRHRCv28PXcusOUxHUE-GZygIDq
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
# Input data files are available in the "../input/" directory.
import os

netflix=pd.read_csv("/content/netflix_titles.csv")

netflix.head(10)

"""#Shape of the dataset"""

netflix.shape

"""#Print the name of columns"""

netflix.columns

"""#Check for NULL Values"""

netflix.isnull().sum()

"""#Check unique values"""

netflix.nunique()

"""#Check for Duplicate values"""

netflix.duplicated().sum()

"""#Make a copy of the dataset"""

df = netflix.copy()

df.shape

"""#Drop NULL values"""

df = df.dropna()

df.shape

"""#Print first 10 values"""

df.head(10)

"""#Convert Date Time format"""

df["date_added"] = pd.to_datetime(df['date_added'])
df['day_added'] = df['date_added'].dt.day
df['year_added'] = df['date_added'].dt.year
df['month_added']=df['date_added'].dt.month
df['year_added'].astype(int);
df['day_added'].astype(int);

df.head(10)

"""#Data Visualization
Type: Movie and TV Shows
"""

sns.countplot(data=netflix, x='type')
fig = plt.gcf()
fig.set_size_inches(10,10)
plt.title('Type')

"""#Rating of shows and movies"""

sns.countplot(data=netflix, x='rating')
sns.countplot(data=netflix, x='rating').set_xticklabels(sns.countplot(data=netflix,x='rating').get_xticklabels(), rotation=90, ha="right")
fig = plt.gcf()
fig.set_size_inches(13,13)
plt.title('Rating')

"""#Relation between Type and Rating"""

plt.figure(figsize=(10,8))
sns.countplot(x='rating',hue='type',data=netflix)
plt.title('Relation between Type and Rating')
plt.show()

"""#Pie-chart for the Type: Movie and TV Shows"""

labels = ['Movie', 'TV show']
size = netflix['type'].value_counts()
colors = plt.cm.Wistia(np.linspace(0, 1, 2))
explode = [0, 0.1]
plt.rcParams['figure.figsize'] = (9, 9)
plt.pie(size,labels=labels, colors = colors, explode = explode, shadow = True, startangle = 80)
plt.title('Distribution of Type', fontsize = 15)
plt.legend()
plt.show()

"""#Pie-chart for Rating"""

netflix['rating'].value_counts().plot.pie(autopct='%1.1f%%',shadow=True,figsize=(10,8))
plt.show()

"""#WordCloud"""

pip install wordcloud

from wordcloud import WordCloud

"""#Country"""

plt.subplots(figsize=(15,10))
wordcloud = WordCloud(
                          background_color='Black',
                          width=1920,
                          height=1080
                         ).generate(" ".join(df.country))
plt.imshow(wordcloud)
plt.axis('off')
plt.savefig('country.png')
plt.show()

"""#Cast in the Shows"""

plt.subplots(figsize=(15,10))
wordcloud = WordCloud(
                          background_color='Black',
                          width=1920,
                          height=1080
                         ).generate(" ".join(df.cast))
plt.imshow(wordcloud)
plt.axis('off')
plt.savefig('cast.png')
plt.show()

"""#Directors"""

plt.subplots(figsize=(15,10))
wordcloud = WordCloud(
                          background_color='black',
                          width=1920,
                          height=1080
                         ).generate(" ".join(df.director))
plt.imshow(wordcloud)
plt.axis('off')
plt.savefig('director.png')
plt.show()

"""#Categories"""

plt.subplots(figsize=(15,10))
wordcloud = WordCloud(
                          background_color='Black',
                          width=1920,
                          height=1080
                         ).generate(" ".join(df.listed_in))
plt.imshow(wordcloud)
plt.axis('off')
plt.savefig('category.png')
plt.show()

"""Data Science plays a role so important in a majority of online services and helps not only bring more customers but keeps the existing ones happy. The reason why is because, with Data Science, you get a more realistic picture of your consumers’ taste in the form of graphs and charts that take not just one metric but several as input. This crucial piece of information helps you in molding your products and services in a way that looks one-of-a-kind to your customers, attracting them to your platform.

With a company like Netflix that is brimming with data, it’s always a wise decision to put that pile of data to good use. By incorporating concepts like data analysis, machine learning, statistics and deep learning, Data Science can help not just Netflix but any business to grow exponentially regardless of sector.

As Reed Hastings said:
Everyone with a phone has a screen and access to the internet. That is our addressable market. The world’s taste, and the world’s time, is what we’re after.

Data Science plays a critical role in not just deciding the functioning of Netflix but also presents them with newer opportunities to grow. New technologies often bring their fair share of issues with them, but at Netflix, they have been tackling those issues head-on, consistently by taking community inputs. By open-sourcing several of the libraries and frameworks to the community, Netflix aims to improve not just itself, but other companies as well. In the end, it would be incorrect to say that Netflix takes all its decisions based on Data Science insights as they still rely on human inputs from a lot of people.

This project aims to build a movie recommendation mechanism and data analysis within Netflix. The dataset I used here come directly from Netflix. Netflix is not only a successful Service But it is completely a Data-Driven Service
"""